<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target
    Name="NpmInstall"
    Inputs="$(PackageJson)"
    Outputs="$(NpmInstallStampFile)"
    Condition="'$(ExecNpmInstallCommand)' == 'true' AND Exists($(PackageJson))">

    <!-- Check if pnpm is installed. -->
    <Exec Command="pnpm -v" IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="PnpmInstalledExitCode" />
    </Exec>

    <!-- Use pnpm if installed. -->
    <Exec Command="$(PnpmInstallCommand)"
          Condition="'$(PnpmInstalledExitCode)' == '0'"
          WorkingDirectory="$(NpmTargetsWorkingDirectory)"
          EnvironmentVariables="@(NpmCommandsEnvironmentVariables)" />
    <!-- Otherwise use regular npm. -->
    <Exec Command="$(NpmInstallCommand)"
          Condition="'$(PnpmInstalledExitCode)' != '0'"
          WorkingDirectory="$(NpmTargetsWorkingDirectory)"
          EnvironmentVariables="@(NpmCommandsEnvironmentVariables)" />

    <!-- Ensure that the node_modules folder exists because we use it for our stamp files. -->
    <MakeDir Directories="$(NodeModulesFolderPath)" Condition="!Exists($(NodeModulesFolderPath))" />
    <Touch Files="$(NpmInstallStampFile)" AlwaysCreate="true" Condition="'$(CreateNpmInstallStampFile)' == 'true'" />
  </Target>

  <Target
    Name="DeleteDotnetPrebuildStampFile"
    AfterTargets="Clean"
    Condition="Exists($(NpmDotnetPrebuildStampFile))">
    <Delete Files="$(NpmDotnetPrebuildStampFile)" />
  </Target>

  <Target
    Name="NpmDotnetPostclean"
    AfterTargets="Clean"
    Condition="'$(ExecDotnetPostcleanCommand)' == 'true' AND Exists($(PackageJson)) AND Exists($(NpmTargetsWorkingDirectory))">
    <Exec Command="$(NpmDotnetPostcleanCommand)"
          WorkingDirectory="$(NpmTargetsWorkingDirectory)"
          EnvironmentVariables="@(NpmCommandsEnvironmentVariables)"
          IgnoreExitCode="true"
          IgnoreStandardErrorWarningFormat="true" />
  </Target>

  <!--
    EmbeddModuleAssets (sic!) was renamed to OrchardCoreEmbedModuleAssets (first released in Orchard Core 1.4), but
    we're keeping it here for backwards compatibility.
  -->
  <Target
    Name="NpmDotnetPrebuild"
    DependsOnTargets="NpmInstall"
    AfterTargets="AfterResolveReferences;InitCommonNodeModules"
    BeforeTargets="EmbeddModuleAssets;OrchardCoreEmbedModuleAssets;Compile"
    Inputs="@(NpmDotnetPrebuildWatchedFiles)"
    Outputs="$(NpmDotnetPrebuildStampFile)"
    Condition="'$(ExecDotnetPrebuildCommand)' == 'true' AND Exists($(PackageJson))">
    <CallTarget Targets="_NpmDotnetPrebuild" />
    <Touch Files="$(NpmDotnetPrebuildStampFile)"
           Condition="'$(CreateDotnetPrebuildStampFile)' == 'true'"
           AlwaysCreate="true" />
  </Target>

  <UsingTask TaskName="CopyVendors"
             TaskFactory="RoslynCodeTaskFactory"
             AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup>
      <ProjectPath ParameterType="System.String" Required="true" />
      <ProjectFilePath ParameterType="System.String" Required="true" />
      <LibraryPath ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="System" />
      <Using Namespace="System.IO" />
      <Using Namespace="System.Linq" />
      <Using Namespace="System.Xml.Linq" />
      <Using Namespace="System.Xml.XPath" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        static void CopyDirectory(DirectoryInfo source, string target)
        {
            Directory.CreateDirectory(target);

            foreach (var file in source.GetFiles())
            {
                file.CopyTo(Path.Combine(target, file.Name));
            }

            foreach (var subdirectory in source.GetDirectories())
            {
                CopyDirectory(subdirectory, Path.Combine(target, subdirectory.Name));
            }
        }

        static void FindVendors(string projectPath, string projectFilePath, Action<string> error, Action<string> warning)
        {
            var document = XDocument.Load(projectFilePath);
            var vendors = document.Root.XPathSelectElements("//ItemGroup/Vendor");
            var targetBase = Path.Combine(projectPath, "wwwroot", "vendor");

            if (!Directory.Exists(targetBase)) Directory.CreateDirectory(targetBase);

            foreach (var vendor in vendors)
            {
                var path = Path.Combine(projectPath, vendor.Attributes("Include").First().Value);
                var name = Path.GetFileName(path);

                if (!Directory.Exists(path))
                {
                    error($"NPM package \"{name}\" does not exist (expected path: \"{path}\").");
                    continue;
                }

                if (vendor.XPathSelectElement("./Subdirectory") is { } subdirectory)
                {
                    path = Path.Combine(path, subdirectory.Value);
                    if (!Directory.Exists(path))
                    {
                        error(
                            $"NPM package \"{name}\" with subdirectory path \"{subdirectory.Value}\" does not exist " +
                            $"(expected path: \"{path}\").");
                        continue;
                    }
                }
                else
                {
                    if (Directory.Exists(Path.Combine(path, "dist")))
                    {
                        path = Path.Combine(path, "dist");
                    }
                    else
                    {
                        warning(
                            $"NPM package item for \"{name}\" does not specify a \u003cSubdirectory\u003e{{value}}" +
                            $"\u003c/Subdirectory\u003e child element and the default \"dist\" subdirectory does not " +
                            $"exist. Please add a \u003cSubdirectory\u003e. Leave it empty if you want to copy the whole " +
                            $"package directory.");
                    }
                }

                var target = Path.Combine(targetBase, name);
                if (Directory.Exists(target)) Directory.Delete(target, recursive: true);
                CopyDirectory(new DirectoryInfo(path), target);
            }
        }

        FindVendors(ProjectPath, ProjectFilePath, text => Log.LogError(text), text => Log.LogWarning(text));
        ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="_NpmDotnetPrebuild">
    <Exec Command="$(NpmDotnetPrebuildCommand)"
          ConsoleToMSBuild="true"
          WorkingDirectory="$(NpmTargetsWorkingDirectory)"
          EnvironmentVariables="@(NpmCommandsEnvironmentVariables)">
      <Output TaskParameter="ConsoleOutput" PropertyName="PrebuildOutput" />
    </Exec>
    <CopyVendors ProjectPath="$(MSBuildProjectDirectory)"
                 ProjectFilePath="$(MSBuildProjectFullPath)"
                 LibraryPath="$(MSBuildThisFileDirectory)" />
  </Target>

</Project>
