<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Base.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.Base.Sdk" Version="2.0.1" />

  <PropertyGroup>
    <Title>Lombiq NPM MSBuild Targets</Title>
    <CopyrightYear>2020</CopyrightYear>
    <DescriptionBody>Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. See the project website for detailed documentation.</DescriptionBody>
    <PackageTags>Lombiq;NPM;Node.js;MSBuild</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/NPM-Targets</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="build/**" Pack="true" PackagePath="build/" />
    <None Include="*.props" Pack="true" PackagePath="" />
    <None Include="*.targets" Pack="true" PackagePath="" />
    <None Remove="node_modules/**" />
    <None Update="build\LoadCopyVendorsTask.targets">
      <Pack>true</Pack>
      <PackagePath>build/</PackagePath>
    </None>
    <None Update="build\LoadExecWithMutexTask.targets">
      <Pack>true</Pack>
      <PackagePath>build/</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="18.8.2" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.8.2" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.8.2" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Base.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.Base.Sdk" Version="2.0.1" />
</Project>
